/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.customer;

import controller.BookingController;
import controller.MovieController;
import controller.ScheduleController;
import view.MainFrame;

/**
 *
 * @author Rillah
 */
public class CustomerPanel extends javax.swing.JPanel {
    private MainFrame mainFrame;
    private MovieController movieCtrl;
    private ScheduleController schCtrl;
    private BookingController bookCtrl;

    /**
     * Creates new form CustomerPanel
     */
    public CustomerPanel(MainFrame mainFrame, MovieController movieCtrl, ScheduleController schCtrl, BookingController bookCtrl) {
        this.movieCtrl = movieCtrl;
        this.schCtrl = schCtrl;
        this.bookCtrl = bookCtrl;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 776, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
